modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/CursedFlames/Modifiers"

license="MIT"
[[mods]]
modId="modifiers"
version="${mod_version}"
displayName="Modifiers"
# A URL for the "homepage" for this mod, displayed in the mod UI
#displayURL="http://example.com/" #optional
issueTrackerURL="https://github.com/CursedFlames/Modifiers/issues"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
# A text field displayed in the mod UI
# credits="Thanks for this example mod goes to Java" #optional
# A text field displayed in the mod UI
authors="CursedFlames"
# The description text for the mod (multi line!) (#mandatory)
description='''
Adds random modifiers to equipment that give minor tweaks to attributes'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.modifiers]] #optional
    # the modid of the dependency
    modId="forge" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[47.0.35,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.modifiers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20,1.21)"
    ordering="NONE"
    side="BOTH"
# TODO put curios dependency here?